# Generated by Django 2.2.6 on 2020-02-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtr',
            name='account',
            field=models.ManyToManyField(blank=True, to='app.Account'),
        ),
    ]
