# Generated by Django 2.2.6 on 2020-02-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dtr_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtr',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
