# Generated by Django 2.2.6 on 2020-02-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200206_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtr',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
