# Generated by Django 2.2.6 on 2020-02-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dtr_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtr',
            name='diff',
            field=models.TimeField(null=True),
        ),
    ]
