# Generated by Django 2.2.6 on 2020-02-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dtr_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtr',
            name='diff',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
