# Generated by Django 2.2.6 on 2020-02-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200206_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtr',
            name='diff',
            field=models.TimeField(null=True),
        ),
    ]
