# Generated by Django 2.2.6 on 2020-02-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200206_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtr',
            name='diff',
        ),
        migrations.AddField(
            model_name='dtr',
            name='hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='minutes',
            field=models.IntegerField(null=True),
        ),
    ]
