# Generated by Django 2.2.6 on 2020-02-10 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200206_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('dtr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DTR')),
            ],
        ),
    ]
