# Generated by Django 2.2.6 on 2020-02-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200210_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtr',
            name='desc',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='dtr',
            table='dtr',
        ),
    ]
